import Head from 'next/head'
import Header from './naduvnoy'
import Navbar from './navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Intex-market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Components */}
      <Navbar />
      <Header />
      
    </div>
  )
}
