import Head from 'next/head'
import Aksessuar from './aksessuar'
import Footer from './footer'
import Karkasniy from './karkasniy'
import Header from './naduvnoy'
import Navbar from './navbar'
import Oformit from './oformit'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Intex-market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Components */}
      <Navbar />
      <Header />
      <Karkasniy />
      <Aksessuar />
      <Oformit />
      <Footer />
    </div>
  )
}
